// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dihayahdlqdnapsbvrtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpaGF5YWhkbHFkbmFwc2J2cnRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDI1MTQsImV4cCI6MjA2NTA3ODUxNH0.JVNIXnZep0GsY0zLWBdL-LIj683Q6l4d-4wqAPM7SqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);